#version: '3'
volumes:
  mariadb-data:
    name: ${PROJECT_NAME}-data

networks:
  network-id:
    name: ${PROJECT_NAME}-network

services:
  mariadb:
    build:
      context: ./docker/mariadb
      args:
        mariadb_version: ${MARIADB_VERSION}
    container_name: ${PROJECT_NAME}-mariadb
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./docker/mariadb/dumps:/docker-entrypoint-initdb.d
    ports:
      - "${MARIADB_PORT}:3306"
    restart: no
    networks:
      - network-id

  php:
    build:
      context: ./docker/php
      args:
        php_version: ${PHP_VERSION}
        document_root: ${DOCUMENT_ROOT}
    extra_hosts:  #Permite la conexión mediante host.docker.internal
      - "host.docker.internal:host-gateway"
    container_name: ${PROJECT_NAME}-php
    ports:
      - "${PHP_PORT}:80"      
    volumes:
      - ./www:/var/www/html
    links:
      - mariadb
    networks:
      - network-id

  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    restart: no
    ports:
      - ${PHPMYADMIN_PORT}:80
    links:
      - mariadb
    environment:      
      PMA_HOST: ${PROJECT_NAME}-mariadb      
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      UPLOAD_LIMIT: 256M
    networks:
      - network-id
